name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up environment
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Run audit
      run: npm audit

    - name: Run linter
      run: npm run lint
